In [1]:
%matplotlib inline
import os
import matplotlib.pyplot as plt
import sys
import pickle
from PIL import Image
from matplotlib.pyplot import imshow
import cv2
import numpy as np
from skimage.color import rgb2gray
import glob
from collections import defaultdict


In [2]:
test_Struct = pickle.load(open( "test_save.p", "rb" ))

In [3]:
Struct = pickle.load( open( "save.p", "rb" ) )

In [4]:
def gen_bbox(structure):
    img_file = defaultdict(list)

    for x in structure:
        img_file[x[0]].append(x[1:])
    
    return img_file

img_file = gen_bbox(Struct)
img_file

defaultdict(list,
            {'4833.png': [[5, 28, 7, 12, 20],
              [2, 40, 7, 8, 20],
              [7, 49, 5, 12, 20]],
             '28190.png': [[6, 35, 11, 8, 17]],
             '25708.png': [[1, 30, 5, 9, 28], [1, 39, 6, 12, 28]],
             '25267.png': [[4, 27, 8, 9, 17],
              [4, 34, 7, 7, 17],
              [1, 41, 8, 7, 17]],
             '27533.png': [[6, 57, 9, 23, 58], [3, 81, 13, 26, 58]],
             '28897.png': [[2, 59, 13, 42, 61], [10, 107, 10, 45, 61]],
             '17899.png': [[1, 37, 2, 13, 37], [8, 49, 1, 21, 37]],
             '8662.png': [[1, 24, 1, 10, 28], [3, 34, 1, 18, 28]],
             '24624.png': [[2, 21, 3, 7, 17], [4, 27, 3, 6, 17]],
             '7299.png': [[1, 80, 17, 18, 71], [10, 97, 17, 34, 71]],
             '10310.png': [[1, 15, 2, 7, 14],
              [1, 19, 3, 6, 14],
              [2, 23, 2, 9, 14]],
             '6405.png': [[4, 65, 25, 14, 25],
              [3, 78, 24, 13, 25],
              [5, 87, 22, 15, 25]

In [5]:
test_img_file = gen_bbox(test_Struct)
test_img_file

defaultdict(list,
            {'4833.png': [[3, 31, 6, 11, 19], [9, 42, 8, 15, 19]],
             '8387.png': [[8, 49, 10, 32, 30]],
             '4525.png': [[1, 73, 12, 10, 23],
              [9, 81, 12, 15, 23],
              [7, 96, 12, 11, 23],
              [2, 108, 10, 15, 23]],
             '10970.png': [[2, 64, 23, 8, 19], [10, 69, 23, 8, 19]],
             '8662.png': [[2, 33, 8, 9, 23], [2, 44, 12, 14, 23]],
             '7651.png': [[2, 32, 4, 9, 18], [7, 41, 5, 15, 18]],
             '10.png': [[1, 16, 19, 7, 21], [6, 26, 19, 12, 21]],
             '6767.png': [[1, 43, 15, 10, 26], [4, 53, 8, 22, 26]],
             '2989.png': [[4, 78, 10, 12, 22], [5, 88, 15, 13, 22]],
             '9727.png': [[4, 60, 80, 38, 66],
              [4, 98, 45, 43, 66],
              [6, 140, 19, 46, 66]],
             '5630.png': [[1, 71, 34, 12, 30], [5, 86, 32, 18, 30]],
             '6405.png': [[7, 108, 11, 14, 34], [8, 119, 14, 14, 34]],
             '12475.png': [[2, 63, 13, 26, 36], [

In [6]:
image_size = 64
#num_labels = 10
num_channels = 1 # grayscale

def reformat(dataset):
  dataset = dataset.reshape(
    (-1, image_size, image_size, num_channels)).astype(np.float32)
  return dataset


In [5]:
def conv_channel(img):
    new_array = np.empty(shape=(img.shape[3], img.shape[0],img.shape[1]), dtype=np.float32)
#new_array[9].shape
    for i in range(img.shape[3]):
        img_single = img[:,:,:,i]
        img_single_gray = rgb2gray(img_single)
        new_array[i] = img_single_gray
    return new_array

In [16]:
conv_channel(reshaped_data).shape

(1, 1, 64)

In [8]:
num_of_data = 13067
def gen_data(files):
    new_array = np.empty(shape=(num_of_data,64,64,1), dtype=np.float32)
    for count, i in enumerate(files.keys()[1:num_of_data]):   #starting index value is 1
        img_path =  os.path.join('train/{}'.format(i))#.format(i)
        img = Image.open(img_path)
    #imshow(img)
        pic = img_file[i]
        labels = [x[0] for x in pic]
        left = [x[1] for x in pic]
        top = [x[2] for x in pic]
        width = [x[3] for x in pic]
        height = [x[4] for x in pic]
    #print labels
        left_bbox = left[0] 
        top_bbox = top[0]
        width_bbox = sum(width)
        height_bbox = height[0]
        box = (left_bbox, top_bbox, left_bbox+width_bbox, top_bbox+height_bbox)

        area = img.crop(box).resize([64,64], Image.ANTIALIAS)
    #imshow(area)
        reshaped_data = reformat(rgb2gray(np.asarray(area)))
    #print reshaped_data.shape
        new_array[count] = reshaped_data
    return new_array


new_array = gen_data(img_file)
new_array

In [9]:
test_new_array = gen_data(test_img_file)

In [10]:
test_new_array

array([[[[ 0.26750785],
         [ 0.26750785],
         [ 0.26750785],
         ..., 
         [ 0.32400116],
         [ 0.33072823],
         [ 0.33773804]],

        [[ 0.26750785],
         [ 0.26750785],
         [ 0.26750785],
         ..., 
         [ 0.32428393],
         [ 0.33101097],
         [ 0.33773804]],

        [[ 0.26750785],
         [ 0.26750785],
         [ 0.26750785],
         ..., 
         [ 0.32456666],
         [ 0.33129373],
         [ 0.33773804]],

        ..., 
        [[ 0.3246043 ],
         [ 0.32852587],
         [ 0.33244744],
         ..., 
         [ 0.37079999],
         [ 0.36771175],
         [ 0.36462352]],

        [[ 0.32852587],
         [ 0.33244744],
         [ 0.33636901],
         ..., 
         [ 0.37472156],
         [ 0.37163332],
         [ 0.36854509]],

        [[ 0.33244744],
         [ 0.33636901],
         [ 0.34029058],
         ..., 
         [ 0.37864313],
         [ 0.37638822],
         [ 0.37329999]]],


       [[[ 0.46396

In [22]:
cv2.imshow('image',test_new_array[-2])
cv2.waitKey(0)
cv2.destroyAllWindows()

In [12]:
def gen_labels(folder, files):
    labels_img = []
    for count, i in enumerate(files.keys()[1:num_of_data]):   #starting index value is 1
        img_path =  os.path.join('{}/{}'.format(folder, i))#.format(i)
        img = Image.open(img_path)
    #imshow(img)
        pic = img_file[i]
        labels = [x[0] for x in pic]
    #five_seq_labels = np.empty(shape=(1,5), dtype=np.uint8)
        five_seq_labels = []
    #print labels[0]
        for s in range(5):
            try:
                if labels[s] == 10:
                    labels[s] = 0
                five_seq_labels.append(labels[s])
            #five_seq_labels[count][s] = labels[s]
            except: 
                five_seq_labels.append(10)
            
        labels_img.append(five_seq_labels)
    return np.array(labels_img)
            #five_seq_labels[count][s] = 10
    #five_seq_labels = np.array(five_seq_labels).flatten()
    #five_seq_labels = (np.arange(11) == five_seq_labels[:,None]).astype(np.float32)
    #labels_img.append(five_seq_labels)  
        #five_seq_labels = five_seq_labels.flatten()    
        #five_seq_labels = (np.arange(11) == five_seq_labels[:,None]).astype(np.float32)
#labels_img = gen_labels('train', img_file)
#labels_img
    #labels_img.append(five_seq_labels)
#print labels_img
#labels_img = np.array(labels_img)
#print labels_img.shape
#five_seq_labels
#five_seq_labels[0][:,None]

In [13]:
labels_test_img = gen_labels('test', test_img_file)
labels_test_img

array([[ 3,  2, 10, 10, 10],
       [ 1,  6,  3, 10, 10],
       [ 2,  5,  5, 10, 10],
       ..., 
       [ 1,  0,  4, 10, 10],
       [ 2,  5,  7, 10, 10],
       [ 5,  4,  2, 10, 10]])

In [18]:
def one_hot_en(lbls):
    labels_dataset = []
    for c in range(num_of_data-1):
        labels_dataset.append((np.arange(11) == lbls[c][:,None]).astype(np.float16))
    return labels_dataset

#labels_dataset = one_hot_en(labels_img)
#labels_dataset

In [19]:
labels_test_dataset = one_hot_en(labels_test_img)
labels_test_dataset

[array([[ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.]], dtype=float16),
 array([[ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.]], dtype=float16),
 array([[ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0

In [22]:
total_data = pickle.dump(new_array, open("total_data.p", "wb" ) )

In [23]:
total_data = pickle.load( open( "total_data.p", "rb" ) )

In [24]:
total_data.shape

(33403, 64, 64, 1)

In [15]:
total_label = pickle.dump(np.array(labels_dataset), open("total_labels.p", "wb" ) )

In [19]:
total_labels = pickle.load( open( "total_labels.p", "rb" ) )

In [29]:
total_labels[-1]

array([[ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.]], dtype=float16)

In [22]:
Sample_test_data = pickle.dump(test_new_array, open("sample_test_data.p", "wb" ) )

In [23]:
Sample_test_data = pickle.load( open( "sample_test_data.p", "rb" ) )
Sample_test_data.shape

(1000, 64, 64, 1)

In [24]:
Sample_test_label = pickle.dump(np.array(labels_test_dataset), open("sample_test_labels.p", "wb" ) )

In [26]:
Sample_test_labels = pickle.load( open( "sample_test_labels.p", "rb" ) )
Sample_test_labels

array([[[ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  1., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  1.],
        [ 0.,  0.,  0., ...,  0.,  0.,  1.]],

       [[ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  1., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  1.],
        [ 0.,  0.,  0., ...,  0.,  0.,  1.],
        [ 0.,  0.,  0., ...,  0.,  0.,  1.]],

       [[ 0.,  1.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  1.],
        [ 0.,  0.,  0., ...,  0.,  0.,  1.]],

       ..., 
       [[ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  1.,  0.,  0.],
        [ 0.,  0.,  1., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  1.]],

       [[ 0.,  0.,  1., ...,  0.,  0.,  0.],
        [ 0.,  0.,  1., ...,  0., 

In [14]:
labels_dataset.shape

AttributeError: 'list' object has no attribute 'shape'

In [100]:
five_seq_labels = np.empty(shape=(1,5), dtype=np.float32)


In [101]:
five_seq_labels[0][0] = 1

In [102]:
five_seq_labels = five_seq_labels.flatten()
five_seq_labels

array([ 1.,  0.,  0.,  0.,  0.], dtype=float32)

In [103]:
labels_2 = (np.arange(10) == five_seq_labels[:,None]).astype(np.float32)

In [28]:
ls = np.array([[6, 10, 10, 10, 10], [6, 10, 10, 10, 10]])

In [30]:
ls[:,None]

array([[[[ 6, 10, 10, 10, 10]]],


       [[[ 6, 10, 10, 10, 10]]]])

In [32]:
ls[0]

array([ 6, 10, 10, 10, 10])

In [20]:
labels_test_dataset[-1]

array([[ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.]], dtype=float16)

In [23]:
#concatanate the numpy arrays
total_test_data = pickle.dump(test_new_array, open("total_test_data.p", "wb" ) )

In [25]:
total_test_data = pickle.load( open( "total_test_data.p", "rb" ) )

In [26]:
total_test_data.shape

(13067, 64, 64, 1)

In [27]:
total_test_label = pickle.dump(np.array(labels_test_dataset), open("total_test_labels.p", "wb" ) )

In [28]:
total_test_labels = pickle.load( open( "total_test_labels.p", "rb" ) )

In [29]:
total_test_labels.shape

(13066, 5, 11)